const cloud = require('wx-server-sdk')

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })

const db = cloud.database()

function normalizeText(value) {
  return String(value || '').trim()
}

function resolveUserDisplayName(user = {}, fallbackValue = '', defaultText = '当前用户') {
  const customDisplayName = normalizeText(user.customDisplayName)
  if (customDisplayName) {
    return customDisplayName
  }

  const wechatNickname = normalizeText(user.wechatNickname || user.nickName)
  if (wechatNickname) {
    return wechatNickname
  }

  const phoneValue = normalizeText(user.phoneMasked || user.phone)
  if (phoneValue) {
    return phoneValue
  }

  return normalizeText(fallbackValue) || defaultText
}

function normalizeTaskType(value) {
  const current = normalizeText(value)
  const allowed = ['send_solution', 'send_quote', 'demo', 'report_solution', 'business_negotiation', 'research', 'callback', 'meeting', 'contract', 'collect_info', 'other']
  return allowed.includes(current) ? current : 'other'
}

function normalizeTaskPriority(value) {
  const current = normalizeText(value)
  const allowed = ['high', 'normal', 'low']
  return allowed.includes(current) ? current : 'normal'
}

function parseDateTime(value, fallback = null) {
  const text = normalizeText(value)
  if (!text) {
    return fallback
  }

  const normalized = text.replace(' ', 'T')
  const date = new Date(normalized)
  if (Number.isNaN(date.getTime())) {
    return fallback
  }

  return date
}

function formatTaskDueText(dueDate, dueTime, dueAt) {
  if (dueDate && dueTime) {
    return `${dueDate} ${dueTime}`
  }

  if (dueDate) {
    return dueDate
  }

  if (!(dueAt instanceof Date) || Number.isNaN(dueAt.getTime())) {
    return ''
  }

  const year = dueAt.getFullYear()
  const month = `${dueAt.getMonth() + 1}`.padStart(2, '0')
  const day = `${dueAt.getDate()}`.padStart(2, '0')
  const hour = `${dueAt.getHours()}`.padStart(2, '0')
  const minute = `${dueAt.getMinutes()}`.padStart(2, '0')
  return `${year}-${month}-${day} ${hour}:${minute}`
}

function buildNextTaskPayload(value) {
  if (!value || typeof value !== 'object') {
    return null
  }

  const title = normalizeText(value.title)
  const description = normalizeText(value.description)
  const dueDate = normalizeText(value.dueDate)
  const dueTime = normalizeText(value.dueTime) || '18:00'
  const hasAnyValue = Boolean(title || description || dueDate || dueTime)

  if (!hasAnyValue) {
    return null
  }

  const dueAt = parseDateTime(`${dueDate} ${dueTime}`, null)
  if (!title || !dueDate || !dueAt) {
    return {
      ok: false,
      message: 'nextTask title and due time are required'
    }
  }

  return {
    ok: true,
    payload: {
      title,
      description,
      type: normalizeTaskType(value.type),
      priority: normalizeTaskPriority(value.priority),
      dueAt,
      dueDateText: formatTaskDueText(dueDate, dueTime, dueAt)
    }
  }
}

function buildTaskDoneFollowUp(task, actorName, resultSummary, now, openid, nextTask) {
  const taskTitle = normalizeText(task && task.title) || '未命名动作'
  const safeResultSummary = normalizeText(resultSummary)
  const nextTaskSummary = nextTask && nextTask.title
    ? `已续接下一步：${nextTask.title}${nextTask.dueDateText ? `（截止 ${nextTask.dueDateText}）` : ''}`
    : ''

  return {
    _openid: openid,
    projectId: task.projectId,
    actorOpenid: openid,
    actorName,
    followUpTime: now,
    method: '动作完成',
    content: safeResultSummary
      ? `已完成推进动作：${taskTitle}\n完成情况：${safeResultSummary}${nextTaskSummary ? `\n${nextTaskSummary}` : ''}`
      : `已完成推进动作：${taskTitle}${nextTaskSummary ? `\n${nextTaskSummary}` : ''}`,
    images: [],
    stageChange: '',
    nextFollowUpTime: '',
    aiSummary: `已完成推进动作「${taskTitle}」`,
    aiHighlights: [safeResultSummary, nextTaskSummary].filter(Boolean),
    aiRisks: [],
    aiRecommendedStage: '',
    aiStageChangeReason: '',
    aiMissingInfo: [],
    sourceTaskId: task._id,
    autoGeneratedByTask: true,
    createdAt: now
  }
}

async function resolveTaskNotifications(openid, projectId, taskId, now) {
  const projectResult = await db.collection('notifications').where({
    _openid: openid,
    projectId
  }).get()

  const closableItems = (projectResult.data || []).filter((item) => {
    const type = normalizeText(item.type)
    const currentTaskId = normalizeText(item.extra && item.extra.taskId)
    return currentTaskId === taskId
      && (type === 'task_due' || type === 'task_overdue' || type === 'task_upcoming')
      && normalizeText(item.status) !== 'resolved'
  })

  if (!closableItems.length) {
    return
  }

  await Promise.all(closableItems.map((item) => {
    return db.collection('notifications').doc(item._id).update({
      data: {
        status: 'resolved',
        readAt: item.readAt || now,
        resolvedAt: now,
        updatedAt: now
      }
    })
  }))
}

async function syncSharedTaskProgress(projectId, actorName, task, followUpId, now) {
  const safeProjectId = normalizeText(projectId)
  if (!safeProjectId) {
    return
  }

  try {
    const projectResult = await db.collection('projects').doc(safeProjectId).get()
    const project = projectResult.data || {}
    const sharedFromOpenid = normalizeText(project.sharedFromOpenid)
    const sourceProjectId = normalizeText(project.sourceProjectId)
    const sourceShareRecordId = normalizeText(project.sourceShareRecordId)

    if (!project.isSharedProject || !sharedFromOpenid || !sourceProjectId || !sourceShareRecordId) {
      return
    }

    await db.collection('shareRecords').doc(sourceShareRecordId).update({
      data: {
        updatedAt: now,
        lastCollaboratorFollowAt: now,
        lastCollaboratorTaskDoneAt: now
      }
    })

    await db.collection('notifications').add({
      data: {
        _openid: sharedFromOpenid,
        type: 'shared_followed',
        level: 'normal',
        title: '对方已继续推进',
        summary: `${actorName} 已完成 ${normalizeText(task && task.title) || '一项推进任务'}，可在外发项目中查看最新进展。`,
        projectId: sourceProjectId,
        projectName: normalizeText(project.projectName) || '未命名项目',
        shareRecordId: sourceShareRecordId,
        sourceOpenid: project._openid || '',
        sourceName: actorName,
        actionUrl: `/pages/project-detail/project-detail?projectId=${sourceProjectId}&view=shared-out`,
        actionLabel: '进入外发项目',
        status: 'unread',
        extra: {
          importedProjectId: safeProjectId,
          taskId: normalizeText(task && task._id),
          followUpId: normalizeText(followUpId),
          sharedFromOpenid,
          receiverOpenid: project._openid || '',
          receiverName: actorName,
          shareMode: 'outbound'
        },
        createdAt: now,
        updatedAt: now
      }
    })
  } catch (error) {
    // Do not block task completion when collaborative progress sync fails.
  }
}

exports.main = async (event) => {
  const wxContext = cloud.getWXContext()
  const taskId = normalizeText(event.taskId)
  const nextStatus = normalizeText(event.status)
  const resultSummary = normalizeText(event.resultSummary)
  const allowedStatuses = ['pending', 'in_progress', 'done', 'canceled']

  if (!taskId || !allowedStatuses.includes(nextStatus)) {
    return {
      ok: false,
      message: 'taskId and status are required'
    }
  }

  if (nextStatus === 'done' && !resultSummary) {
    return {
      ok: false,
      message: 'resultSummary is required when task is done'
    }
  }

  const nextTaskResult = buildNextTaskPayload(event.nextTask)
  if (nextTaskResult && nextTaskResult.ok === false) {
    return {
      ok: false,
      message: nextTaskResult.message
    }
  }
  const nextTaskPayload = nextTaskResult && nextTaskResult.ok ? nextTaskResult.payload : null

  const taskResult = await db.collection('tasks').where({
    _id: taskId,
    _openid: wxContext.OPENID
  }).limit(1).get()

  if (!taskResult.data.length) {
    return {
      ok: false,
      message: 'task not found'
    }
  }

  const currentTask = taskResult.data[0]
  const now = new Date()
  const userResult = await db.collection('users').where({
    _openid: wxContext.OPENID
  }).limit(1).get()
  const actorProfile = userResult.data[0] || {}
  const actorName = resolveUserDisplayName(actorProfile)

  const updatePayload = {
    status: nextStatus,
    updatedAt: now
  }

  if (nextStatus === 'in_progress') {
    updatePayload.startedAt = currentTask.startedAt || now
  }

  if (nextStatus === 'done') {
    updatePayload.completedAt = now
    updatePayload.completedByOpenid = wxContext.OPENID
    updatePayload.completedByName = actorName
    updatePayload.canceledAt = null
    updatePayload.canceledByOpenid = ''
    updatePayload.canceledByName = ''
    if (resultSummary) {
      updatePayload.resultSummary = resultSummary
    }
  }

  if (nextStatus === 'canceled') {
    updatePayload.canceledAt = now
    updatePayload.canceledByOpenid = wxContext.OPENID
    updatePayload.canceledByName = actorName
  }

  if (nextStatus === 'pending') {
    updatePayload.startedAt = null
  }

  await db.collection('tasks').doc(taskId).update({
    data: updatePayload
  })

  let followUpId = ''
  if (nextStatus === 'done') {
    const existingFollowUp = await db.collection('followUps').where({
      _openid: wxContext.OPENID,
      projectId: currentTask.projectId,
      sourceTaskId: currentTask._id
    }).limit(1).get()

    if (!existingFollowUp.data.length) {
      const followUpResult = await db.collection('followUps').add({
        data: buildTaskDoneFollowUp(currentTask, actorName, resultSummary, now, wxContext.OPENID, nextTaskPayload)
      })
      followUpId = followUpResult._id
    } else {
      followUpId = existingFollowUp.data[0]._id
    }
  }

  if (nextTaskPayload) {
    await db.collection('tasks').add({
      data: {
        _openid: wxContext.OPENID,
        projectId: currentTask.projectId,
        sourceFollowUpId: followUpId || '',
        ownerOpenid: wxContext.OPENID,
        ownerName: actorName,
        creatorOpenid: wxContext.OPENID,
        creatorName: actorName,
        title: nextTaskPayload.title,
        type: nextTaskPayload.type,
        priority: nextTaskPayload.priority,
        status: 'pending',
        dueAt: nextTaskPayload.dueAt,
        dueDateText: nextTaskPayload.dueDateText,
        description: nextTaskPayload.description,
        resultSummary: '',
        createdAt: now,
        updatedAt: now,
        startedAt: null,
        completedAt: null,
        completedByOpenid: '',
        completedByName: '',
        canceledAt: null,
        canceledByOpenid: '',
        canceledByName: ''
      }
    })
  }

  if (currentTask.projectId) {
    const projectUpdatePayload = {
      updatedAt: now
    }

    await db.collection('projects').doc(currentTask.projectId).update({
      data: projectUpdatePayload
    })
  }

  if ((nextStatus === 'done' || nextStatus === 'canceled') && currentTask.projectId) {
    try {
      await resolveTaskNotifications(wxContext.OPENID, currentTask.projectId, currentTask._id, now)
    } catch (error) {
      // Do not block task completion when notification sync fails.
    }
  }

  if (nextStatus === 'done') {
    await syncSharedTaskProgress(currentTask.projectId, actorName, currentTask, followUpId, now)
  }

  return {
    ok: true,
    taskId,
    status: nextStatus,
    updatedAt: now,
    nextTaskCreated: !!nextTaskPayload
  }
}
